global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.30.135:9090']
  - job_name: "toktik-api"
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.30.135:9190']
  - job_name: "toktik-user"
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.30.135:9191' ]
  - job_name: "toktik-interaction"
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.30.135:9192' ]
  - job_name: "toktik-video"
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.30.135:9193' ]
  - job_name: "toktik-chat"
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.30.135:9194' ]
  - job_name: "toktik-favor"
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.30.135:9195' ]
  - job_name: "toktik-comment"
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.30.135:9196' ]